build:
  version: prodprofileisactive
card:
  message: "prod card user is active"
  contactDetails:
    phoneNumber: 9997865023
    email: "prodpalprashant18970@gmail.com"
  instaId:
    - "prodpalprashant283"
    - "prodpalprashant18970"
spring:  
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


    hibernate:
      ddl-auto: update
